// Baked travel data — auto-generated by .github/workflows/bake.yml from the
// Google Sheet (via the Apps Script gate's ?action=mapdata endpoint).
//
// This committed copy is SEED data so the map renders before the first bake.
// It will be overwritten on the next sheet edit / workflow run. Do not hand-edit
// for real data — edit the Google Sheet instead.
//
// Shape: { "<ISO2>": { name: "<Country>", visits: <number> }, ... }
window.TRAVEL_DATA = {
  "LK": { "name": "Sri Lanka", "visits": 15 },
  "SG": { "name": "Singapore", "visits": 20 },
  "MY": { "name": "Malaysia", "visits": 6 },
  "AU": { "name": "Australia", "visits": 3 },
  "GB": { "name": "United Kingdom", "visits": 2 },
  "TH": { "name": "Thailand", "visits": 4 },
  "IN": { "name": "India", "visits": 5 },
  "AE": { "name": "United Arab Emirates", "visits": 3 },
  "ID": { "name": "Indonesia", "visits": 2 },
  "JP": { "name": "Japan", "visits": 1 }
};
