// Baked travel data — auto-generated by .github/workflows/bake.yml from the
// Google Sheet (via the Apps Script gate). Do not hand-edit; edit the Sheet.
window.TRAVEL_DATA = {
  "SG": {
    "name": "Singapore",
    "visits": 1
  },
  "LK": {
    "name": "Sri Lanka",
    "visits": 10
  },
  "NZ": {
    "name": "New Zealand",
    "visits": 3
  },
  "IN": {
    "name": "India",
    "visits": 1
  },
  "AU": {
    "name": "Australia",
    "visits": 2
  },
  "NO": {
    "name": "Norway",
    "visits": 1
  },
  "VN": {
    "name": "Vietnam",
    "visits": 1
  },
  "MY": {
    "name": "Malaysia",
    "visits": 2
  },
  "ID": {
    "name": "Indonesia",
    "visits": 1
  }
};

window.TRAVEL_TRIPS = [{"iso2":"SG","name":"Singapore","arr":"2022-06","dep":"2022-09"},{"iso2":"LK","name":"Sri Lanka","arr":"2022-09","dep":"2022-11"},{"iso2":"NZ","name":"New Zealand","arr":"2022-11","dep":"2022-11"},{"iso2":"NZ","name":"New Zealand","arr":"2023-05","dep":"2023-05"},{"iso2":"IN","name":"India","arr":"2023-08","dep":"2023-09"},{"iso2":"LK","name":"Sri Lanka","arr":"2023-11","dep":"2023-11"},{"iso2":"AU","name":"Australia","arr":"2024-04","dep":"2024-04"},{"iso2":"NZ","name":"New Zealand","arr":"2024-04","dep":"2024-04"},{"iso2":"LK","name":"Sri Lanka","arr":"2024-09","dep":"2024-09"},{"iso2":"AU","name":"Australia","arr":"2025-02","dep":"2025-03"},{"iso2":"NO","name":"Norway","arr":"2018-06","dep":"2018-06"},{"iso2":"VN","name":"Vietnam","arr":"2023-10","dep":"2023-10"},{"iso2":"MY","name":"Malaysia","arr":"2023-12","dep":"2023-12"},{"iso2":"MY","name":"Malaysia","arr":"2025-11","dep":"2025-11"},{"iso2":"ID","name":"Indonesia","arr":"2026-07","dep":"2026-07"},{"iso2":"LK","name":"Sri Lanka","arr":"2023-04","dep":"2023-04"},{"iso2":"LK","name":"Sri Lanka","arr":"2024-07","dep":"2024-08"},{"iso2":"LK","name":"Sri Lanka","arr":"2025-06","dep":"2025-06"},{"iso2":"LK","name":"Sri Lanka","arr":"2025-08","dep":"2025-09"},{"iso2":"LK","name":"Sri Lanka","arr":"2026-01","dep":"2026-01"},{"iso2":"LK","name":"Sri Lanka","arr":"2026-03","dep":"2026-03"},{"iso2":"LK","name":"Sri Lanka","arr":"2026-08","dep":"2026-08"}];

window.TRAVEL_VISAS = [{"iso2":"NO","name":"Norway","from":"2018-04","until":"2018-06","type":"Schengen (C)"},{"iso2":"IN","name":"India","from":"2023-08","until":"2023-10","type":"e-Visa (tourist)"},{"iso2":"ID","name":"Indonesia","from":"2026-07","until":"2026-08","type":"Visa C1"},{"iso2":"ES","name":"Spain","from":"2026-04","until":"2026-05","type":"Schengen (C)"}];
