// Baked travel data — auto-generated by .github/workflows/bake.yml from the
// Google Sheet (via the Apps Script gate). Do not hand-edit; edit the Sheet.
window.TRAVEL_DATA = {
  "SG": {
    "name": "Singapore",
    "visits": 1
  },
  "LK": {
    "name": "Sri Lanka",
    "visits": 3
  },
  "NZ": {
    "name": "New Zealand",
    "visits": 3
  },
  "IN": {
    "name": "India",
    "visits": 1
  },
  "AU": {
    "name": "Australia",
    "visits": 2
  },
  "NO": {
    "name": "Norway",
    "visits": 1
  },
  "VN": {
    "name": "Vietnam",
    "visits": 1
  },
  "MY": {
    "name": "Malaysia",
    "visits": 2
  },
  "ID": {
    "name": "Indonesia",
    "visits": 1
  }
};
